[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
  "yt_dlp",
  "feedparser",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
  "--import-mode=importlib",
]
